// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBI5IAP1oqHQEJzHfvORuv151BPq5cDzxA',
    appId: '1:242354888660:web:b16ec38809ead92d780041',
    messagingSenderId: '242354888660',
    projectId: 'homeautomation-ee5cd',
    authDomain: 'homeautomation-ee5cd.firebaseapp.com',
    storageBucket: 'homeautomation-ee5cd.firebasestorage.app',
    measurementId: 'G-0V5Z4C9TNJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChw85-Ysf05Ji8PZcK73BZJAtzVdr1xrc',
    appId: '1:242354888660:android:9bab0fe909880d91780041',
    messagingSenderId: '242354888660',
    projectId: 'homeautomation-ee5cd',
    storageBucket: 'homeautomation-ee5cd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCz2Z9WuJQgki9ykz_a8Lv0zx2O2BG1-Os',
    appId: '1:242354888660:ios:e59364644c44469c780041',
    messagingSenderId: '242354888660',
    projectId: 'homeautomation-ee5cd',
    storageBucket: 'homeautomation-ee5cd.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCz2Z9WuJQgki9ykz_a8Lv0zx2O2BG1-Os',
    appId: '1:242354888660:ios:e59364644c44469c780041',
    messagingSenderId: '242354888660',
    projectId: 'homeautomation-ee5cd',
    storageBucket: 'homeautomation-ee5cd.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBI5IAP1oqHQEJzHfvORuv151BPq5cDzxA',
    appId: '1:242354888660:web:6f2b73dfc8d7586d780041',
    messagingSenderId: '242354888660',
    projectId: 'homeautomation-ee5cd',
    authDomain: 'homeautomation-ee5cd.firebaseapp.com',
    storageBucket: 'homeautomation-ee5cd.firebasestorage.app',
    measurementId: 'G-GRZT5STVPR',
  );
}
